# Generated by Django 3.0.6 on 2020-06-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200531_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='hashtag',
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
    ]
